### ISSUE TITLE
Support Traditional Ethiopian calendar (13 months)

### ISSUE THREAD

**Issue by amenk** [mikimaine/ethiopian-calendar#3]
Is it possible to use the traditional calendar where we are right now in the year 2010 and which has 13 months?

**Comment by mikimaine** [comment]
It already supports 13 months, 12 months with 30 days and 13th month with 5/6 day based on leap year.

https://github.com/mikimaine/ethiopian-calendar/blob/60a5dab4af9e6edfd228e0ee525726559b9e56b5/src/ethiopian.calendars.js#L26

**Comment by amenk** [comment]
Thank you
